---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concourse
  namespace: concourse-flux-poc
  labels:
    app: concourse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concourse
  template:
    metadata:
      labels:
        app: concourse
    spec:
      containers:
      - name: concourse
        image: concourse/concourse:3.14.1
        args: ["quickstart"]
        ports:
        - containerPort: 8080
        env:
        - name: CONCOURSE_POSTGRES_HOST
          value: concourse-db
        - name: CONCOURSE_POSTGRES_USER
          value: concourse_user
        - name: CONCOURSE_POSTGRES_PASSWORD
          value: concourse_pass
        - name: CONCOURSE_POSTGRES_DATABASE
          value: concourse
        - name: CONCOURSE_EXTERNAL_URL
          value: "http://concourse.minikube:8080"
        - name: CONCOURSE_ADD_LOCAL_USER
          value: test:$$2a$$10$$0W9/ilCpYXY/yCPpaOD.6eCrGda/fnH3D4lhsw1Mze0WTID5BuiTW
        - name: CONCOURSE_MAIN_TEAM_ALLOW_ALL_USERS
          value: "true"
        - name: CONCOURSE_WORKER_GARDEN_NETWORK
          value: ""
        - name: CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH
          value: "true"
        securityContext:
          privileged: true
