---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-demoapp
  namespace: concourse-flux-poc
  labels:
    app: go-demoapp
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-demoapp
  template:
    metadata:
      labels:
        app: go-demoapp
    spec:
      containers:
      - name: go-demoapp
        image: microwaves/go-demoapp:0.2.14
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
